createHashMapFromArray [
    ["schemaVersion", 1],
    ["addon", "z_amcp_main"],
    ["actions", [
        "bridge.ping",
        "bridge.get_capabilities",
        "eden.get_status",
        "eden.get_selection",
        "eden.list_entities",
        "eden.find_entities",
        "eden.get_entity_snapshot",
        "eden.get_entities",
        "eden.get_entity_attributes",
        "assets.search_classes",
        "terrain.sample_area",
        "eden.create_entity",
        "eden.set_entity_transform",
        "eden.set_entity_attributes",
        "eden.append_init",
        "eden.delete_entities",
        "eden.set_selection",
        "eden.clear_selection",
        "eden.focus_entities",
        "eden.batch",
        "eden.validate_plan",
        "eden.capture_composition",
        "eden.apply_composition",
        "eden.get_connections",
        "eden.get_synced",
        "eden.sync_entities",
        "eden.unsync_entities",
        "eden.list_layers",
        "eden.create_layer",
        "eden.assign_layer",
        "eden.remove_from_layer",
        "eden.set_layer_attributes",
        "eden.delete_layer",
        "assets.get_class",
        "terrain.find_flat_area",
        "terrain.find_nearest_roads",
        "spatial.check_collision",
        "spatial.score_placement",
        "spatial.line_of_sight",
        "spatial.find_cover_positions",
        "spatial.find_lz_candidates",
        "catalog.scanStart",
        "catalog.scanChunk",
        "catalog.scanFinish",
        "catalog.measureClass",
        "camera.createPreviewScene",
        "camera.inspectClass",
        "camera.captureClassAngles",
        "camera.captureCurrentView",
        "camera.destroyPreviewScene"
    ]],
    ["features", createHashMapFromArray [
        ["typedActions", true],
        ["entityRegistry", true],
        ["readSnapshots", true],
        ["writeBatch", true],
        ["composition", true],
        ["layers", true],
        ["connections", true],
        ["catalogScan", true],
        ["catalogMeasurement", true],
        ["spatialValidation", true],
        ["screenshotCapture", true],
        ["cameraControl", true],
        ["rawSqf", false],
        ["historyGrouping", true]
    ]]
]
