createHashMapFromArray [
    ["schemaVersion", 1],
    ["addon", "z_amcp_main"],
    ["actions", [
        "bridge.ping",
        "bridge.get_capabilities",
        "eden.get_status",
        "eden.get_selection",
        "eden.list_entities",
        "eden.find_entities",
        "eden.get_entity_snapshot",
        "eden.get_entities",
        "eden.get_entity_attributes",
        "assets.search_classes",
        "terrain.sample_area",
        "eden.create_entity",
        "eden.set_entity_transform",
        "eden.set_entity_attributes",
        "eden.append_init",
        "eden.delete_entities",
        "eden.set_selection",
        "eden.clear_selection",
        "eden.focus_entities",
        "eden.batch",
        "eden.validate_plan",
        "eden.capture_composition",
        "eden.apply_composition",
        "catalog.scanStart",
        "catalog.scanChunk",
        "catalog.scanFinish"
    ]],
    ["features", createHashMapFromArray [
        ["typedActions", true],
        ["entityRegistry", true],
        ["readSnapshots", true],
        ["writeBatch", true],
        ["composition", true],
        ["catalogScan", true],
        ["rawSqf", false],
        ["historyGrouping", true]
    ]]
]
